version: '3'
services:
  postgres:
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
  redis:
    image: redis
    restart: unless-stopped
  superset:
    build:
      context: .
      args:
        SUPERSET_VERSION: 0.25.0
    image: terminal1/superset
    depends_on:
      - postgres
      - redis
    volumes:
      - ./superset_config.py:/etc/superset/superset_config.py
    ports:
      - "127.0.0.1:8088:8088"
volumes:
  postgres:
    external: false
  redis:
    external: false
